//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuyken.VeGasCo.Backend.Infrastructure.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nuyken.Vegasco.Backend.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string InfoMessageAutoMigrationDisabled {
            get {
                return ResourceManager.GetString("InfoMessageAutoMigrationDisabled", resourceCulture);
            }
        }
        
        internal static string InfoMessageFetchingDbOptions {
            get {
                return ResourceManager.GetString("InfoMessageFetchingDbOptions", resourceCulture);
            }
        }
        
        internal static string InfoMessageMigratingDatabase {
            get {
                return ResourceManager.GetString("InfoMessageMigratingDatabase", resourceCulture);
            }
        }
        
        internal static string InfoMessageMigrationSuccessful {
            get {
                return ResourceManager.GetString("InfoMessageMigrationSuccessful", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnableToRetrieve {
            get {
                return ResourceManager.GetString("ErrorMessageUnableToRetrieve", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnexpectedMigrationError {
            get {
                return ResourceManager.GetString("ErrorMessageUnexpectedMigrationError", resourceCulture);
            }
        }
    }
}
