//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuyken.VeGasCo.Backend.Application.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nuyken.Vegasco.Backend.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DebugMessageEntityCreated {
            get {
                return ResourceManager.GetString("DebugMessageEntityCreated", resourceCulture);
            }
        }
        
        internal static string DebugMessageEntityUpdated {
            get {
                return ResourceManager.GetString("DebugMessageEntityUpdated", resourceCulture);
            }
        }
        
        internal static string DebugMessageUploadedSettingsForUser {
            get {
                return ResourceManager.GetString("DebugMessageUploadedSettingsForUser", resourceCulture);
            }
        }
        
        internal static string ErrorMessageBehaviourNoData {
            get {
                return ResourceManager.GetString("ErrorMessageBehaviourNoData", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUserWithIdAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMessageUserWithIdAlreadyExists", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationAnyDataNeeded {
            get {
                return ResourceManager.GetString("ErrorMessageValidationAnyDataNeeded", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyBodyRouteMismatch {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyBodyRouteMismatch", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyContainsInvalidCharacters", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyInFuture {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyInFuture", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyInvalidValue {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyInvalidValue", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyMustBeGreaterOrEqualToZero {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyMustBeGreaterOrEqualToZero", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyNotFoundForUser {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyNotFoundForUser", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationPropertyNotProvided {
            get {
                return ResourceManager.GetString("ErrorMessageValidationPropertyNotProvided", resourceCulture);
            }
        }
        
        internal static string ErrorMessageValidationRouteIdEmptyOrDefaultGuid {
            get {
                return ResourceManager.GetString("ErrorMessageValidationRouteIdEmptyOrDefaultGuid", resourceCulture);
            }
        }
        
        internal static string InfoMessageSavedSettingsForUser {
            get {
                return ResourceManager.GetString("InfoMessageSavedSettingsForUser", resourceCulture);
            }
        }
        
        internal static string InfoMessageUserCreatedEntity {
            get {
                return ResourceManager.GetString("InfoMessageUserCreatedEntity", resourceCulture);
            }
        }
        
        internal static string InfoMessageUserDeletedEntity {
            get {
                return ResourceManager.GetString("InfoMessageUserDeletedEntity", resourceCulture);
            }
        }
        
        internal static string InfoMessageUserUpdatedEntity {
            get {
                return ResourceManager.GetString("InfoMessageUserUpdatedEntity", resourceCulture);
            }
        }
        
        internal static string JwtUsernameIdentifier {
            get {
                return ResourceManager.GetString("JwtUsernameIdentifier", resourceCulture);
            }
        }
        
        internal static string ValidationRegexValidCharacters {
            get {
                return ResourceManager.GetString("ValidationRegexValidCharacters", resourceCulture);
            }
        }
        
        internal static string DuplicateEntryErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateEntryErrorMessage", resourceCulture);
            }
        }
    }
}
