//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nuyken.VeGasCo.Backend.WebApi.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Nuyken.Vegasco.Backend.WebApi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ErrorMessageEntityNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageEntityNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorMessageInvalidData {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidData", resourceCulture);
            }
        }
        
        internal static string ErrorMessageInvalidOrMissingConfigurationOption {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidOrMissingConfigurationOption", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnexpectedError {
            get {
                return ResourceManager.GetString("ErrorMessageUnexpectedError", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnexpectedHostTermination {
            get {
                return ResourceManager.GetString("ErrorMessageUnexpectedHostTermination", resourceCulture);
            }
        }
        
        internal static string ExceptionMiddlewareUnexpectedError {
            get {
                return ResourceManager.GetString("ExceptionMiddlewareUnexpectedError", resourceCulture);
            }
        }
        
        internal static string ExceptionMiddlewareUnexpectedErrorWithUrl {
            get {
                return ResourceManager.GetString("ExceptionMiddlewareUnexpectedErrorWithUrl", resourceCulture);
            }
        }
        
        internal static string DuplicateEntryErrorMessage {
            get {
                return ResourceManager.GetString("DuplicateEntryErrorMessage", resourceCulture);
            }
        }
        
        internal static string ErrorMessageUnauthorized {
            get {
                return ResourceManager.GetString("ErrorMessageUnauthorized", resourceCulture);
            }
        }
    }
}
